### ISSUE TITLE
[p.407, 문의] 모듈패키지 버전과 타입패키지 버전 호환성 확인 방법

### ISSUE THREAD

**Issue by wiseguy77** [ZeroCho/ts-book#21]
예제의 express@4.18.2 와 @types/express@4.17.17 은 모두 가장 최신 버전으로 확인됩니다.
그리고 @types/express@4.17.17 깃헙에서 버전별로 호환되는 ts 버전도 확인할 수 있었습니다.
그런데 모듈패키지와 타입패키지의 버전 호환 정보는 찾지 못했습니다. 

모듈패키지와 타입패키지 간 호환 정보를 확인할 수 있는 방법이 있을까요?

**Comment by ZeroCho** [comment]
보통 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-kakao/index.d.ts#L1

이런 식으로 어떤 버전의 타입인지 index.d.ts 파일에 나와 있습니다.

**Comment by wiseguy77** [comment]
확인했습니다. 고맙습니다.
