### ISSUE TITLE
[p.424, 제안] 위에서 2~3번째 줄 

### ISSUE THREAD

**Issue by wiseguy77** [ZeroCho/ts-book#26]
~~req.session은~~(-> req.session의 타입은) session 네임스페이스의 SessionData ~~인터페이스를 상속하고~~ (-> 인터페이스이고), ~~req.user는~~ (-> req.user의 타입은) Express 네임스페이스의 User 인터페이스이므로 ...

**Comment by ZeroCho** [comment]
session.Session &은 상속의 의미라서(p85) 상속한다고 표현했습니다.

**Comment by wiseguy77** [comment]
네, 저도 그렇게 이해했습니다.
다만, req.session 자체가 타입이 아닌 속성이기 때문에 'SessionData 인터페이스를 상속했다'는 표현보다 SessionData를 상속한 인터페이스 타입의 속성이다.
라는 의미면 더 좋지 않을까 하는 의도였습니다. 

고맙습니다~
