### ISSUE TITLE
[p.383, 문의] 맨 위 Note의 예시 모듈

### ISSUE THREAD

**Issue by wiseguy77** [ZeroCho/ts-book#45]
[p.382] 에서 path 모듈은 CommonJs 방식이라 'export = 와 import =  ' 문법을 사용하고 있다고 했는데,
[p.383] Note 에서 export * as [네임스페이스] from [모듈명] 문법이 CommonJs 방식 path 모듈을 예로 설명되고 있습니다.
이 방식은 EMS 방식을 사용한 모듈(fs모듈 또는 http모듈)에서 가능한 방식 아닌가요?

**Comment by ZeroCho** [comment]
export * as [네임스페이스] from [모듈명]은 ESM에만 국한된 사용법이 아닙니다!

**Comment by wiseguy77** [comment]
아하 그렇군요. 답변 고맙습니다!

**Comment by ZeroCho** [comment]
이번에도 책에 있는 오타 잘 찾아주시고 좋은 제안도 많이 해 주셔서(대부분 2쇄에 반영될 예정입니다) 감사의 의미로 내년에 나오는 자바스크립트 입문서도 출간 후 보내드리겠습니다! 혹시 필요하시면 인프런 타입스크립트 강좌도 공짜로 드리겠습니다(책 내용과 거의 동일). 감사합니다!
